version: '2'
services:
  chat_redis:
    extends:
      file: docker-compose-common.yml
      service: chat_redis

  auth_redis:
    extends:
      file: docker-compose-common.yml
      service: auth_redis

  elasticsearch:
    extends:
      file: docker-compose-common.yml
      service: elasticsearch

  auth:
    extends:
      file: docker-compose-common.yml
      service: auth
    links:
      - auth_redis
      - elasticsearch
    depends_on:
      - auth_redis
      - elasticsearch

  web:
    extends:
      file: docker-compose-common.yml
      service: web
    links:
      - chat_redis
      - elasticsearch
      - auth
    depends_on:
      - chat_redis
      - elasticsearch
      - auth

  lb:
    extends:
      file: docker-compose-common.yml
      service: lb
    links:
      - web
    depends_on:
      - web

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  auth-redis-data:
    driver: local
